# Generated by Django 5.1.15 on 2026-09-23 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfertaFonte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_externo", models.CharField(blank=True, max_length=50)),
                ("nome_externo", models.CharField(max_length=200)),
                ("url_fonte", models.URLField()),
                ("ativo", models.BooleanField(default=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="catalogo.produto",
                    ),
                ),
                (
                    "supermercado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ofertas",
                        to="catalogo.supermercado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_hora_coleta", models.DateTimeField()),
                (
                    "oferta_fonte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precos",
                        to="precos.ofertafonte",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_hora_coleta"],
            },
        ),
    ]
